services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myappdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306" # Maps local port 3307 -> container port 3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: